#!/bin/sh

-export([refresh_sessions_created_at/0]).
-export([refresh_cvv_encryption/0]).
-export([refresh_cardholder_encryption/0]).


set -e

REL_NAME=cds
SCRIPT_NAME=maintenance
maintenance_usage() {
    command="$1"

    case "$command" in
        refresh_sessions_created_at)
            echo "Usage: $SCRIPT_NAME refresh_sessions_created_at"
            echo "Sets sessions \"created at\" time to current UTC time"
            ;;
        refresh_cvv_encryption)
            echo "Usage: $SCRIPT_NAME refresh_cvv_encryption"
            echo "Sets sessions \"key id\" index to the current one"
            ;;
        refresh_cardholder_encryption)
            echo "Usage: $SCRIPT_NAME refresh_cardholder_encryption"
            echo "Sets tokens \"key id\" index to the current one"
            ;;
        *)
            echo "Usage: $SCRIPT_NAME {refresh_sessions_created_at|refresh_cvv_encryption|refresh_cardholder_encryption|help}"
            ;;
    esac
}

# Check the first argument for instructions
case "$1" in
    refresh_sessions_created_at)
        (exec ./$REL_NAME eval 'cds_maintenance:refresh_sessions_created_at()')
        ;;
    refresh_cvv_encryption)
        (exec ./$REL_NAME eval 'cds_maintenance:refresh_cvv_encryption()')
        ;;
    refresh_cardholder_encryption)
        (exec ./$REL_NAME eval 'cds_maintenance:refresh_cardholder_encryption()')
        ;;
    help)
        if [ -z "$2" ]; then
            maintenance_usage
            exit 1
        fi

        TOPIC="$2"; shift
        maintenance_usage $TOPIC
        ;;
    *)
        maintenance_usage
        exit 1
        ;;
esac

exit 0
