#!/bin/sh

set -e

REL_NAME=cds
SCRIPT_NAME=maintenance
maintenance_usage() {
    command="$1"

    case "$command" in
        refresh_sessions)
            echo "Usage: $SCRIPT_NAME refresh_sessions"
            echo "Sets sessions \"created at\" time to current UTC time"
            ;;
        reencrypt_cvv)
            echo "Usage: $SCRIPT_NAME reencrypt_cvv"
            echo "Sets sessions \"key id\" index to the current one"
            ;;
        reencrypt_cardholder)
            echo "Usage: $SCRIPT_NAME reencrypt_cardholder"
            echo "Sets tokens \"key id\" index to the current one"
            ;;
        *)
            echo "Usage: $SCRIPT_NAME {refresh_sessions|reencrypt_cvv|reencrypt_cardholder|help}"
            ;;
    esac
}

# Check the first argument for instructions
case "$1" in
    refresh_sessions)
        (exec ./$REL_NAME eval 'cds_maintenance:refresh_sessions_created_at()')
        ;;
    reencrypt_cvv)
        (exec ./$REL_NAME eval 'cds_maintenance:refresh_cvv_encryption()')
        ;;
    reencrypt_cardholder)
        (exec ./$REL_NAME eval 'cds_maintenance:refresh_cardholder_encryption()')
        ;;
    help)
        if [ -z "$2" ]; then
            maintenance_usage
            exit 1
        fi

        TOPIC="$2"; shift
        maintenance_usage $TOPIC
        ;;
    *)
        maintenance_usage
        exit 1
        ;;
esac

exit 0
